site_name: SecOps Guide
site_url: https://secops.guiode
theme:
  name: material
  icon:
    logo: material/shield-outline
  favicon: 
  features:
    - navigation.footer
    
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Home: index.md
  - Detections:
    - Overview: detection_engineering/de_overview.md
    - Metrics: detection_engineering/de_metrics.md
  - Incident Response:
    - Overview: incident_response/ir_overview.md
  - Threat Intelligence:
    - Overview: threat_intelligence/ti_overview.md
  - Automation:
    - Overview: automation/automation_overview.md
  - Vulnerability Management:
    - Overview: vulnerability_management/vm_overview.md
  - About: about.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scottponte/secops-guide